services:
  db:
    image: postgres:17
    container_name: beer_database_postgres_api
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./script_sql:/docker-entrypoint-initdb.d/

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beer_api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env 
    volumes:
      - .:/usr/src/API_BEER  # Monte le répertoire local dans le conteneur

volumes:
  postgres_data:
