services:
  db:
    image: postgres:17
    container_name: beer_database_postgres_api
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./script_sql:/docker-entrypoint-initdb.d/ 

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beer_api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env 
    volumes:
      - .:/usr/src/beer-api  # Monte le répertoire local dans le conteneur
    command: npm run dev

volumes:
  postgres_data:
